//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mykisskui
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bookmark
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Image { get; set; }
        public string URL { get; set; }
    }
}
